# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-11 14:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('root', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.Farming')),
            ],
        ),
        migrations.CreateModel(
            name='Seed_Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('day', models.DateField()),
                ('price', models.FloatField()),
                ('no_of_units_bought', models.IntegerField()),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.Delivery')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.Farming')),
                ('transaction_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.Transaction_Type')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='fund',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seed.Seed_Transaction'),
        ),
    ]
