# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-11 14:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('root', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fruit_Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('day', models.DateField()),
                ('price', models.FloatField()),
                ('no_of_units_sold', models.IntegerField()),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.Delivery')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.Farming')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('yields', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.Yield')),
            ],
        ),
    ]
