# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-11 14:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=256, null=True)),
                ('specialty', models.CharField(max_length=256, null=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Crop_Life_Cycle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.CharField(max_length=256)),
                ('image', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('day', models.DateField()),
                ('day_count', models.IntegerField()),
                ('cost_service', models.FloatField()),
                ('cost_for_day', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Crop_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=256, null=True)),
                ('specialty', models.CharField(max_length=256, null=True)),
                ('region_grown', models.CharField(max_length=256, null=True)),
                ('description', models.TextField()),
                ('time_for_yield', models.IntegerField()),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.Crop')),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=256)),
                ('status', models.CharField(max_length=256)),
                ('from_address', models.TextField()),
                ('to_address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=256, null=True)),
                ('name', models.CharField(max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Farm_Land_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=256, null=True)),
                ('total_area', models.FloatField()),
                ('date_joining', models.DateField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('address', models.TextField()),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.Crop')),
                ('crop_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.Crop_Type')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.District')),
            ],
        ),
        migrations.CreateModel(
            name='Farmer_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, null=True)),
                ('full_name', models.CharField(max_length=256, null=True)),
                ('qualification_details', models.TextField()),
                ('date_joining', models.DateField()),
                ('mobile', models.IntegerField(default=0)),
                ('address', models.TextField()),
                ('detailed_history', models.TextField()),
                ('account_details', models.TextField()),
                ('account_number', models.IntegerField()),
                ('idproof_type', models.CharField(choices=[('Adhaar', 'Adhaar'), ('VoterId', 'VoterId'), ('RationId', 'RationId'), ('PanId', 'PanId'), ('Other', 'Other')], max_length=25)),
                ('proof_number', models.CharField(max_length=256, null=True)),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.Farmer_Details')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.District')),
            ],
        ),
        migrations.CreateModel(
            name='Farming',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('expected_end_date', models.DateField()),
                ('no_of_units', models.IntegerField(default=0)),
                ('no_of_units_for_fund', models.IntegerField()),
                ('no_of_units_funded', models.IntegerField()),
                ('estimated_yield', models.FloatField()),
                ('crop_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.Crop_Type')),
                ('farmer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.Farmer_Details')),
            ],
        ),
        migrations.CreateModel(
            name='Farming_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(choices=[('Organic', 'Organic'), ('In Organinc', 'In_Organic'), ('No Pestisided & No Fertilizer', 'No_Pestisides_&_No_Fertilizer')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Officer_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, null=True)),
                ('full_name', models.CharField(max_length=256, null=True)),
                ('email', models.EmailField(max_length=256)),
                ('qualification_details', models.TextField()),
                ('date_joining', models.DateField()),
                ('mobile', models.IntegerField(default=0)),
                ('address', models.TextField()),
                ('idproof_type', models.CharField(choices=[('Adhaar', 'Adhaar'), ('VoterId', 'VoterId'), ('RationId', 'RationId'), ('PanId', 'PanId'), ('Other', 'Other')], max_length=25)),
                ('proof_number', models.CharField(max_length=256, null=True)),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.Officer_Details')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.District')),
            ],
        ),
        migrations.CreateModel(
            name='Service_Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=256, null=True)),
                ('specialization', models.CharField(max_length=256, null=True)),
                ('contact', models.CharField(max_length=256, null=True)),
                ('address', models.TextField()),
                ('since', models.DateField()),
                ('Sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.Crop')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=256, null=True)),
                ('name', models.CharField(max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Taluk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=256, null=True)),
                ('name', models.CharField(max_length=256, null=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.District')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.State')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(choices=[('Philanthropic', 'Philanthropic'), ('investment for crop', 'investment_for_crop'), ('investment on intrest', 'investment on intrest')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=256, null=True)),
                ('name', models.CharField(max_length=256, null=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.District')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.State')),
                ('taluk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.Taluk')),
            ],
        ),
        migrations.CreateModel(
            name='Yield',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.CharField(max_length=256)),
                ('image', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('day', models.DateField()),
                ('day_count', models.IntegerField()),
                ('estimated_cost', models.FloatField()),
                ('cost_end_of_farm', models.FloatField()),
                ('estimated_yield', models.FloatField()),
                ('final_yield', models.FloatField()),
                ('spend_per_unit', models.FloatField()),
                ('our_price_quote_per_unit', models.FloatField()),
                ('market_price_per_unit', models.FloatField()),
                ('no_of_units_sold_fruit', models.IntegerField()),
                ('no_of_units_to_seed', models.IntegerField()),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.Farming')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.Service_Provider')),
            ],
        ),
        migrations.AddField(
            model_name='officer_details',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.State'),
        ),
        migrations.AddField(
            model_name='officer_details',
            name='taluk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.Taluk'),
        ),
        migrations.AddField(
            model_name='officer_details',
            name='village',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.Village'),
        ),
        migrations.AddField(
            model_name='farming',
            name='farming_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.Farming_Type'),
        ),
        migrations.AddField(
            model_name='farming',
            name='land',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.Farm_Land_Details'),
        ),
        migrations.AddField(
            model_name='farming',
            name='officer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.Officer_Details'),
        ),
        migrations.AddField(
            model_name='farmer_details',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.State'),
        ),
        migrations.AddField(
            model_name='farmer_details',
            name='taluk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.Taluk'),
        ),
        migrations.AddField(
            model_name='farmer_details',
            name='village',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.Village'),
        ),
        migrations.AddField(
            model_name='farm_land_details',
            name='farmer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.Farmer_Details'),
        ),
        migrations.AddField(
            model_name='farm_land_details',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.State'),
        ),
        migrations.AddField(
            model_name='farm_land_details',
            name='taluk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.Taluk'),
        ),
        migrations.AddField(
            model_name='farm_land_details',
            name='village',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.Village'),
        ),
        migrations.AddField(
            model_name='district',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.State'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='service_provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.Service_Provider'),
        ),
        migrations.AddField(
            model_name='crop_life_cycle',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.Farming'),
        ),
        migrations.AddField(
            model_name='crop_life_cycle',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.Service_Provider'),
        ),
    ]
